CREATE PROCEDURE [dbo].[PR_S_PIB]
	 
	 @NOME_CIDADE VARCHAR(MAX) = NULL

AS
BEGIN
	
	SELECT  TOP 5
		 ID_PIB
		,POSICAO
		,CIDADE
		,VALOR
		,PERCENTUAL_RELATIVO
		,PERCENTUAL_TOTAL
		,COORDENADA_X
		,COORDENADA_Y
	FROM
		TB_PIB
	WHERE 
		((@NOME_CIDADE IS NULL) OR  (CIDADE LIKE '%'+@NOME_CIDADE+'%'))
	ORDER BY 
		POSICAO
END